### ISSUE TITLE
centos 6.7 uptime -s useless

### ISSUE THREAD

**Issue by bubifengyun** [abhi1693/yii2-system-info#2]
I see your code, that in centos 6.7 final, it will show nothing when run `uptime -s`

i find the result from `uptime -s`

```
Usage: uptime [-V]
 -V display version
```

**Comment by abhi1693** [comment]
@bubifengyun I'm little confused with what you are saying. Can you please elaborate? As far as I know, `uptime -p` shows the uptime in `pretty format` whereas `uptime -s` simple shows you since when the system is up. I don't understand the issue over here.

**Comment by bubifengyun** [comment]
my  mean  is that 

the  command  `uptime  -s` can  run  in my  deepin Linux  which  is  based on debian . it  can  not  run in centos 6.7 final which is installed in  Min .

the version  of `uptime` in centos has no such `-s` or `-p` options.

could  you understand? sorry  for my bad English .

**Comment by abhi1693** [comment]
Send me a `PR` and I will merge the changes. I don't have `Centos`, so I cannot confirm the changes that I will make in the program.

**Comment by bubifengyun** [comment]
sorry , I do not  know how to solve it .
